# Generated by Django 3.0.5 on 2020-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True, verbose_name='URL')),
                ('short_url', models.CharField(max_length=20)),
            ],
        ),
    ]
