# Generated by Django 3.0.5 on 2020-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200505_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_short',
            name='long_url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='model_short',
            name='short_url',
            field=models.SlugField(default=''),
        ),
    ]
