# Generated by Django 3.0.5 on 2020-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200505_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_short',
            name='short_url',
            field=models.UUIDField(),
        ),
    ]
