# Generated by Django 3.0.5 on 2020-05-06 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200506_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_short',
            name='short_url',
            field=models.UUIDField(default=uuid.UUID('bbd61db9-38d6-4e85-b896-abda874deb68')),
        ),
    ]
