# Generated by Django 3.0.5 on 2020-05-07 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200507_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_short',
            name='short_url',
            field=models.UUIDField(default=uuid.UUID('eb2bea0f-80e2-44e1-b8ea-0c9867bc881e')),
        ),
    ]
